### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by wyhinton** [SergioBenitez/state#12]
Hello!

I'm very interested in this crate. However, I think getting started would be much aided by a couple of minimal examples? Do this exist somewhere? If any exist maybe they could be added to the .readme?

**Comment by SergioBenitez** [comment]
The rustdocs (https://docs.rs/state) have quite a number of examples. Does those not suffice?

**Comment by SergioBenitez** [comment]
I'm assuming yes! Let me know if there's something missing.

**Comment by wyhinton** [comment]
I suppose I was looking for more examples that would demonstrate how to use state to design components. For example, if we have many ```Button``` structs which we'd like to each have an ```on/off``` state, and on some event I'd like to toggle their state from on to off, then I'm a little unsure about how to go about using this library. I know that the library can do global mutable statics, but what if we want to manage state within a bunch of structs?
