### ISSUE TITLE
Thread local state in Container without Send

### ISSUE THREAD

**Issue by droundy** [SergioBenitez/state#3]
It would be ideal to be able to have non-Send types in thread local storage in a container. As long as they stay on the thread, that should work, right?

An alternate solution would be to create a separate thread local version of Container.

**Comment by SergioBenitez** [comment]
We could certainly have an analogous `LocalContainer` struct.

Can you tell me more about your use-case? In particular, do you have types that are `Sync` but not `Send`, or types that are neither?

**Comment by droundy** [comment]
My types are neither Sync nor Send.

**Comment by vorot93** [comment]
[GObject/GTK+ is neither Sync nor send](https://github.com/gtk-rs/examples/blob/master/src/bin/multithreading_context.rs)

**Comment by SergioBenitez** [comment]
@vorot93 I'd really like to implement this, and I even started implementing it. The challenge is doing it in a way that doesn't result in a complete duplication of every type. That, it would be a shame to have two versions of most types in this library: one for `Sync + Send`, and another without the bounds.
