### ISSUE TITLE
Container Iterator

### ISSUE THREAD

**Issue by SOF3** [SergioBenitez/state#6]
There is no way to list all values from Container.
Getting an iterator is probably not very useful since values have distinct types. What I really need is to have a way to debug-print the Container.

**Comment by SergioBenitez** [comment]
There's no way to implement this safely unless we add a `Debug` bound to all `set` methods. I'm not sure the trade-off is worth it. This is reminiscent of #3 where what we'd _really_ like is to have some sort of polymorphic trait bounds. In some pseudo-Rust, we might write:

```rust
struct Container[B: TraitBounds](...);

impl Container[B] {
    fn set<T: B>(..) { .. }
}

impl[B: Debug] Debug for Container[B] {

}
```

Alas, this does not exist in Rust. The alternative is to have different versions of `Container` with different bounds, or to have a macro that somehow safely generates a definition for `Container`.

**Comment by SOF3** [comment]
What is missing in Rust here?

**Comment by SergioBenitez** [comment]
I've come up with a mechanism to make something ~like this work, albeit not fully generically. If you or anyone would like to implement variants of `Container` with `Debug` bounds, feel free to do so.

**Comment by SergioBenitez** [comment]
`Container` now implemented a very basic `Debug`. I think this is as good as it gets, given all of the type erasure.
